Repository MetroCS/redistricting, pull requests merged in 2019-11, with the labels that each got.

#24 Vision update2 based on master
  Vision.md
Labels: documentation

#26 Generate districts code
  src/swdmt/redistricting/AllDistrictGen.java
  src/swdmt/redistricting/Redistrictor.java
  src/swdmt/redistricting/RedistrictorTest.java
  src/swdmt/redistricting/Region.java
  src/swdmt/redistricting/StarGenerator.java
Labels: enhancement

#39 Party
  src/swdmt/redistricting/Party.java
  src/swdmt/redistricting/PartyTest.java
Labels: enhancement

#42 Update Party.java to change UNAFFILIATED display char from '*' to 'U'
  src/swdmt/redistricting/Party.java
  src/swdmt/redistricting/PartyTest.java
Labels: bug

#43 Add basic ASCII-graphic rendering
  src/swdmt/redistricting/RedistrictingDriver.java
  src/swdmt/redistricting/Renderer.java
  src/swdmt/redistricting/RendererTest.java
Labels: enhancement
